name: CI/CD — Build, Publish (GHCR) e Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_WEB: ghcr.io/${{ github.repository }}-web
  IMAGE_API: ghcr.io/${{ github.repository }}-api
  # Ajuste se precisar apontar para outra API
  VITE_API_BASE: https://api.xml.lojasrealce.shop

jobs:
  verify:
    name: Verificar build do projeto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar deps (web)
        run: npm ci

      - name: Build (web)
        run: npm run build

      - name: Instalar deps (api)
        working-directory: server
        run: npm ci --omit=dev

      # Opcional: rode testes se existirem
      # - name: Testes (api)
      #   working-directory: server
      #   run: npm test --if-present

  publish:
    name: Build e publicar imagens no GHCR
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e push — Web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.web
          push: true
          build-args: |
            VITE_API_BASE=${{ env.VITE_API_BASE }}
          tags: |
            ${{ env.IMAGE_WEB }}:latest
            ${{ env.IMAGE_WEB }}:${{ github.sha }}

      - name: Build e push — API
        uses: docker/build-push-action@v6
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.sha }}

  deploy:
    name: Deploy em servidor (opcional)
    needs: publish
    if: ${{ vars.DEPLOY_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Executar deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            echo "📦 Login no GHCR"
            if [ -n "${GHCR_USER}" ] && [ -n "${GHCR_TOKEN}" ]; then
              echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            fi
            echo "📁 Indo para a pasta do projeto"
            cd "${DEPLOY_PATH}"
            echo "⬇️ Pull das imagens"
            docker compose pull
            echo "🚀 Subindo containers"
            docker compose up -d --remove-orphans
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}


